### ISSUE TITLE
github headers

### ISSUE THREAD

**Issue by alex-moreno** [cebe/markdown#100]
Github has the possibility to add header information, something like:

---
layout: post
title: "My post"
description: ""
category: blog
author: alex_moreno
comments: true
share: true
---

is that possible with your implementation? I'd like to contribute that back if possible, could you quickly guide me?

Thanks in advance, good job :-).

**Comment by cebe** [comment]
what do you mean with "Github has the possibility to add header information"? where would I add them and what would be the result?
The syntax you gave above is for link references.

**Comment by josegonzalez** [comment]
@alex-moreno do you mean jekyll?

**Comment by alex-moreno** [comment]
Yep, sorry, yekyll. Thinking later, that should  probably not be
implemented here.

**Comment by cebe** [comment]
You can write an extension for this then.
