### ISSUE TITLE
Creole wiki parser

### ISSUE THREAD

**Issue by softark** [cebe/markdown#102]
I wrote a Creole wiki parser as an extension to the Parser class. It's a sibling of the Markdown class.

You can see it in the "creole" branch of my fork.
https://github.com/softark/markdown/tree/creole

Well, then, I think I have two options now.

1. Making a PR to include this creole "flavor" directly in your markdown parser library.
2. Restructuring the code to make it a separated library that depends on your library.

Which do you think is more appropriate?

**Comment by cebe** [comment]
cool, but I think this deserves its own repository as it is not markdown but another markup language.

**Comment by softark** [comment]
OK. Thanks.
I'll create a repository for it.

**Comment by softark** [comment]
Done.
https://github.com/softark/creole

**Comment by cebe** [comment]
Added it to the list of extensions in the readme: https://github.com/cebe/markdown/commit/e14d3da8f84eefa3792fd22b5b5ecba9c98d2e18

**Comment by softark** [comment]
Thank you.
