### ISSUE TITLE
OPCode cache breaks the parsing of inline elements

### ISSUE THREAD

**Issue by softark** [cebe/markdown#103]
With some OPCode cache enabled, Parser::inlineMarksers() returns an empty array since the docComments has been removed from the source code in the runtime. As a consequence, we won't be able to parse any inline elements.

Tested with PHP 5.6.3 and Zend OPCache 7.0.4-dev / XAMPP 5.6.3 for Windows.

**Comment by samdark** [comment]
There's a setting for it: `opcache.save_comments=1`.

**Comment by softark** [comment]
I got it. Thanks.

But it looks to me a drawback, anyway.

**Comment by cebe** [comment]
the parser depends on phpdoc annotation to work properly. I do not have any plans to change this.
Could check for the setting and throw a warning though.

**Comment by softark** [comment]
OK.
And it has to be noted in the documentation, I think.

**Comment by ypnos-web** [comment]
It would've saved my some time of research if this would've put out a warning. Encourage you to implement such a warning.

**Comment by cebe** [comment]
this is noted in the readme already: https://github.com/cebe/markdown#installation-
