### ISSUE TITLE
==== not parse

### ISSUE THREAD

**Issue by djfly** [cebe/markdown#104]
`=====` not parse 
# 

`=====`  in github is parse to a line

and

`>123` not parse but github can parse

`> 123` need add space behind  `>`

**Comment by djfly** [comment]
There is another problem about table
·········
1   | 2  | 3 | 4 | 5
----- | ----- | ------ | ----- | -----
1  | 2 | 3  |  | 
1  | 2 | 3  | 4 | 5
1  | 2 | 3  | 4 | 5
············

Did not fill in the content of the cell will be lost

**Comment by cebe** [comment]
`====` is not a horizontal rule according to the markdown syntax description: https://daringfireball.net/projects/markdown/syntax#hr

`>123` is also not part of the markdown description, but I will consider adding it.

> Did not fill in the content of the cell will be lost

what do you mean, please explain in more detail.

**Comment by djfly** [comment]
look this
![123](http://chuantu.biz/t2/6/1430302041x-954498848.png)

**Comment by cebe** [comment]
you can add enough pipes there to get it right: http://markdown.cebe.cc/try?flavor=gfm&text=1+|+2+|+3+|+4+|+5%0D%0A-----+|+-----+|+------+|+-----+|+-----%0D%0A1+|+2+|+3+|++++|+|%0D%0A1+|+2+|+3+|+4+|+5%0D%0A1+|+2+|+3+|+4+|+5

**Comment by djfly** [comment]
thank you very much,your project is awesome
