### ISSUE TITLE
about anchor generate

### ISSUE THREAD

**Issue by djfly** [cebe/markdown#105]
in github if you write `#` or `##` `==` `---` this will generate anchor at the same time.
````
<h1>
<a id="user-content-yii-php-framework-version-2" class="anchor" href="#yii-php-framework-version-2" aria-hidden="true"><span class="octicon octicon-link"></span></a>Yii PHP Framework Version 2</h1>
````

 your markdown have this features? how to open this features.

**Comment by cebe** [comment]
You can add it yourself by overriding the `renderHeadline()` method like this:

https://github.com/yiisoft/yii2-apidoc/blob/0636763d08c00a383c19e8a52383618acbb5f224/helpers/ApiMarkdown.php#L80-L88

**Comment by djfly** [comment]
thank you！
