### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by dlmwolf** [cebe/markdown#108]
I want to add a Expansion,but i don't know how to do this.
So submit this issues.
I want to the `[ ]` to `<input type="checkbox">`.
and the  `[x]` to `<input type="checkbox" checked="checked">`.
Thanks for look that.

**Comment by cebe** [comment]
duplicate of #29

**Comment by dlmwolf** [comment]
@cebe Thank you

**Comment by cebe** [comment]
you have to change the parsing of list elements: https://github.com/cebe/markdown/blob/master/block/ListTrait.php#L71
