### ISSUE TITLE
Metadata support?

### ISSUE THREAD

**Issue by mindplay-dk** [cebe/markdown#109]
Thoughts on adding support for [metadata](http://hiltmon.com/blog/2012/06/18/markdown-metadata/)?

I don't think this would be difficult to implement - I happen to need it, and I'm using your library, so wondering if you would be interested in a PR adding support for it.

My use-case is pretty trivial, I need a title and possibly a short title for generating menus for a static website from markdown files - but this could have lots of nice applications, e.g. meta descriptions or marginalia in documents in content management systems that use markdown.

**Comment by josegonzalez** [comment]
@mindplay-dk maybe take a look at how jekyll does frontmatter? It's pretty easy to extract that via a regex :)

**Comment by mindplay-dk** [comment]
Yeah, it's not that I think it would be very difficult, but I think it might be generally useful :-)

**Comment by nochso** [comment]
The most common variation I've seen is "YAML front matter". Keeps it readable and doesn't introduce yet another syntax/ML.

**Comment by mindplay-dk** [comment]
> The most common variation I've seen is "YAML front matter". Keeps it readable and doesn't introduce yet another syntax/ML.

Yeah, but YAML *is* another syntax. YAML front matter is basically delimiters around a YAML document embedded at the beginning of the document.

YAML is not Markdown - if it's embedded in that way, it would not render correctly in a regular Markdown renderer that does not explicitly support it. (Does GitHub support it?)

Preferable to the custom "front matter" syntax used by Jekyll, I think would be a simple GitHub flavored triple-backtick delimited YAML or JSON code block at the top - which would render correctly in e.g. GitHub, Stash or BitBucket.

I might personally even prefer to just add a matching `.yaml` or `.json` file to accompany every `.md` file - again, both would render correctly when viewed in a source browser.

In fact, I don't know why I didn't think of that right away. I think I will go that route for the thing I'm working on here, I find it much cleaner - so for my sake, you can close this thread :-)

**Comment by cebe** [comment]
I do not really think it fits into the library, how would the API look like for this? We have one method that gets markdown in and returns html. Where to return the meta data?

**Comment by cebe** [comment]
Also I think meta data should not be part of the data itself so an extra file sounds more appropriate.

**Comment by mindplay-dk** [comment]
> Where to return the meta data?

If somebody did want to implement this, I was thinking a separate method, so e.g.:

```php
$markdown->enableMeta(); // enables metadata support
$metadata = $markdown->parseMeta($md); // returns an array (or model of some sort)
$html = $markdown->parse($md); // ignores/removes the metadata section
```

The extra file approach, come to think of it, works when you have Markdown files - but it's no use when you're working with a CMS. (Of course, in a CMS you could have other UI surrounding Markdown inputs, so maybe that's a moot point as well...)

**Comment by mindplay-dk** [comment]
Hmm, front matter does seems to be the de-facto standard, and there are several libraries out there that can parse it independently of a Markdown parser. My choice fell on [this one](https://github.com/kzykhys/YamlFrontMatter).

**Comment by Luceos** [comment]
@cebe are you sure you will not support frontmatters in your package? 

- If yes, would you mind me forking yours adding the logic and re-distributing it under a different name?
- If no, can you give me some pointers how to write tests for them?

@mindplay-dk my current implementation is that you can simply add a trait and the respective meta is parsed automatically:

```php
use cebe\markdown\GithubMarkdown;
use cebe\markdown\meta\JsonFrontMatter;

class Markdown extends GithubMarkdown
{
    use JsonFrontMatter;
}
```
Actually retrieving meta:

```php
$contents = $this->markdown->parse($contents);
$meta = $this->markdown->getMeta();
```

https://github.com/hyn/markdown/tree/frontmatters

**Comment by cebe** [comment]
@Luceos there is no need to fork my library for this, you can make a package that is able to do this like the following (basically something like an adapter pattern):

```php
<?php

class FrontMatterMarkdown // feel free to choose a better name :)
{
    // make the markdown parser class and its properties configurable
    public $parser = \cebe\markdown\Markdown::class;
    public $parserConfig = [];

    // other properties for configuring frontmatter behavior may be added here

    public function parse($text)
    {
        // split the $text into frontmatter and markdown here,
        // $markdown will contain the markdown content without fronmatter

        $parser = new $this->parser();
        foreach($this->parserConfig as $p => $v) {
            $parser->$p = $v;
        }
        return $parser->parse($markdown);
    }

    public function getMeta($text)
    {
        // do your magic here
    }
```

That package will depend on my library in composer.json. I can also add a link to it in my readme if you like. 

Forking my library is not a good idea in this case because it will not allow users to combine different features. If I release a new version and you have not updated your fork, users are stuck with that. If you link your lib via composer to mine markdown can be updated independently of the frontmatter implementation. I want this lib to be focused on markdown only to keep a single purpose. Frontmatter is external to markdown and can easily built around it as shown above.

**Comment by Luceos** [comment]
@cebe thanks for your feedback, I hadn't considered either of those options yet. I'll probably follow up on the ioc version, it makes most sense and allows most flexility to the user.

**Comment by Luceos** [comment]
The package is [hyn/frontmatter](https://github.com/hyn/frontmatter) for whoever has the same question, including @mindplay-dk

**Comment by cebe** [comment]
Nice! added it to the README: https://github.com/cebe/markdown/blob/master/README.md#extensions
