### ISSUE TITLE
**A****B** error

### ISSUE THREAD

**Issue by zinzinday** [cebe/markdown#111]
markdown **A****B** only parse to `<strong>A</strong>` and **B**
I want parse to `<strong>A</strong><strong>B</strong>`
how to fix that?

**Comment by samdark** [comment]
Should it produce `<strong>A</strong><strong>B</strong>`?

**Comment by zinzinday** [comment]
Yes. i want to that

**Comment by cebe** [comment]
yeah I know, see #26

**Comment by cebe** [comment]
`**\* ABC**` is fixed on master now.
