### ISSUE TITLE
A small change request in Parser class

### ISSUE THREAD

**Issue by olegkrivtsov** [cebe/markdown#113]
Hi,

First of all thanks for this great library. It's really awesome!

I'm trying to use this library in my project. I want to extend the Markdown class and override its parse() and parseBlocks() methods (inherited from Parser class), but I can't do that because some fields/methods in Parser class are private.

So, my change request is:
  - make Parser::_depth property protected instead of private;
  - make Parser::_blockTypes property protected instead of private;
  - make Parser::_inlineMarkers property protected instead of private;
  - make Parser::prepareMarkers() method protected instead of private 

Is it possible?

**Comment by josegonzalez** [comment]
:+1:

**Comment by cebe** [comment]
In general I am against making private properties protected. As soon as they are protected they belong to the API that I have to maintain backward compatibility for. If there are good reasons to expose some properties I may change their visibility though.

> make Parser::_depth property protected instead of private;

$_depth is only for handling the $maximumNestingLevel, can you elaborate on why you need to access it?

> make Parser::_blockTypes property protected instead of private;

what is the point of making this protected? It is an internal cache of the `blockTypes()` method and not used in any other place. You may just call `blockTypes()` to get its value.

> make Parser::_inlineMarkers property protected instead of private;

this is only used by parseInline(), you are talking about overriding parse() and parseBlocks()...?

> make Parser::prepareMarkers() method protected instead of private 

This is the only change I see as useful right now.

**Comment by olegkrivtsov** [comment]
Hi,

Thanks for your response.

When I'm trying to override Markdown::parse(), I have an error "Method missing prepareMarkers : prepareMarkers", because Parser::prepareMarkers() method is private. If you declare it as protected, I will be able to use it in a derived class.

When I'm trying to override Mardown::parseBlocks() method, I can't get access to the _depth, because it is private. Making it protected is the only way to access it.

If you make these two changes, I'll be able to use your library.

**Comment by josegonzalez** [comment]
In general, anything `protected` or `private` can be removed from the library. Those are explicitly not public interfaces. Therefore, I think the only thing you are doing is stoping people from "mucking" with internals. If you have a way to set properties used in protected methods, that works, but otherwise private properties should only be used by private methods.

**Comment by cebe** [comment]
> In general, anything protected or private can be removed from the library.

not if the library is created in a way that it is meant to be extensible. In this case I explicitly document how to extend the parser to add more markdown elements. So protected methods are part of the interface that is maintained and should not be broken.

> but otherwise private properties should only be used by private methods.

This is a completely valid use case for private properties imo:

```php
private $_label;

public function setLabel($label)
{
    $this->_label = trim($label);
}

public function getLabel()
{
    return $this->_label;
}
```

**Comment by cebe** [comment]
> When I'm trying to override Mardown::parseBlocks() method, I can't get access to the _depth, because it is private. Making it protected is the only way to access it.

@olegkrivtsov can you explain why you want to extend `parseBlocks()`?

**Comment by olegkrivtsov** [comment]
> @olegkrivtsov can you explain why you want to extend parseBlocks()?

I want to extend standard Markdown in a way that would allow to add a property list before any block-level element, for example like this:

```
{width=50%, float=left}
![Title](images/image1.png)
```

This is a Leanpub-flawoured Markdown.

Here is my class: https://github.com/olegkrivtsov/openbook/blob/master/src/OpenBook/Markdown/LeanpubMarkdown.php

**Comment by cebe** [comment]
@olegkrivtsov I have changed the logic of parseBlocks() to call a new method parseBlock() for each new block. Does this solve your problem?

**Comment by olegkrivtsov** [comment]
It solves my problem partially. Besides parsing blocks differently, I also need to split absy by chapters and render each chapter to different html file. You can determine what I want to do if you look at this file: https://github.com/olegkrivtsov/openbook/blob/master/src/OpenBook/Markdown/LeanpubMarkdown.php

**Comment by josegonzalez** [comment]
@olegkrivtsov omg can you make that `LeanpubMarkdown` parser a standalone composer package?

**Comment by olegkrivtsov** [comment]
> @olegkrivtsov omg can you make that LeanpubMarkdown parser a standalone composer package?

@josegonzalez I wat thinking of that

**Comment by cebe** [comment]
@olegkrivtsov what is missing? I don't see it from the code.

**Comment by olegkrivtsov** [comment]
@cebe OK, it solves my needs for now. Thank you.

**Comment by olegkrivtsov** [comment]
Hi @cebe I've tried to use the enhancements you made, but they only partially satisfy my needs.
 
I need to split blocks by chapters, so each chapter will be rendered to a separate HTML file. I can do this with the current version of your code (by overriding `parse()` method and enumerating top-level absy blocks), but the problem is with cross-linking elements. A `[cross-link](#element-id)` may link to any element with "id" attribute. To correctly render links, I have to determine in what HTML file what element is located. To determine in which chapter which element will go, I would have to somehow enumerate all blocks (not only top-level ones), but this is difficult to do inside of `parse()` method (because each block type has each own structure). It would be much easier to do that inside of `parseBlocks()` method, if you made the changes I requested previously. Can you help?

**Comment by cebe** [comment]
@olegkrivtsov could you open a new issue for that? Will look into that later.
