### ISSUE TITLE
How to prevent xss attach ?

### ISSUE THREAD

**Issue by euclid1990** [cebe/markdown#116]
I write following Markdown:
```
<script>alert(1);</script>
```
And using GithubMarkdown, But the parsed result show alert popup, how to sanitize it ?

**Comment by samdark** [comment]
Using HTMLPurifier.

**Comment by euclid1990** [comment]
@samdark Can you give me this git repository ? :smile:

**Comment by cebe** [comment]
https://packagist.org/packages/ezyang/htmlpurifier
