### ISSUE TITLE
Is it possible to extend an inline element to behave like a block element?

### ISSUE THREAD

**Issue by samhastings** [cebe/markdown#117]
I've extended your library to render a markdown image tag inside a `<figure>` element with alt text displayed in a `<figcaption>` element:

``` php
class Markdown extends \cebe\markdown\GithubMarkdown
{
    protected function renderImage($block)
    {
        if (isset($block['refkey'])) {
            $ref = $this->lookupReference($block['refkey']);

            if (false === $ref) {
                return $block['orig'];
            }

            $block = array_merge($block, $ref);
        }

        return sprintf(
            '<figure><img src="%s" alt=""><figcaption>%s</figcaption></figure>',
            htmlentities($block['url'], ENT_QUOTES),
            $block['text']
        );
    }
}
```

This almost works perfectly but with a slight hitch: the `<figure>` element is wrapped in `<p>...</p>` tags, which isn't valid HTML.

Is there any way of making the parser recognise this as a block element, thereby omitting the paragraph tags?

**Comment by cebe** [comment]
This is not really possible because image is an inline element and the structure of the document is already finished at this point. if you add images on a single line you could introduce an image block by detecting lines begining with `![` and create an image block element.
