### ISSUE TITLE
Slack syntax integration

### ISSUE THREAD

**Issue by Soullivaneuh** [cebe/markdown#118]
Slack have a "special" markdown syntax: https://api.slack.com/docs/formatting

It would be great to have two things:
- Standard markdown to Slack markdown converter
- Slack markdown to HTML markdown converter

What do you think?

**Comment by cebe** [comment]
in general this could be useful in some ways, but unless someone is willing to work on this, I am not going to add it. Also not really sure whether this belongs here.
