### ISSUE TITLE
Installation Instructions Need To Be Clearer

### ISSUE THREAD

**Issue by WadeShuler** [cebe/markdown#122]
I just wasted a few minutes messing with your extension. I would create a pull request, but I am fairly busy.

You don't show an example or mention that you need to echo the `$parser->parse($markdown)`

It should be like this (I am using GitHub version):

    $markdown = file_get_contents( Yii::getAlias('@app/../todo.md') );
    
    $parser = new \cebe\markdown\GithubMarkdown();
    echo $parser->parse($markdown);

I was confused at first, wondering why I had a blank page 👍

**Comment by cebe** [comment]
added some echos, better now?
