### ISSUE TITLE
Github flavoured markdown parse code blocks in list incorrectly

### ISSUE THREAD

**Issue by snakevil** [cebe/markdown#132]
For the following markdown source,

`````` markdown
1. foo

    ```
    bar

    blah

    foo
    ```
``````

we're expecting it would be parsed to,

``` html
<li><p>foo</p>
<pre><code>bar

blah

foo</code></pre>
</li>
```

but the output in fact is,

``` html
<li><p>foo</p>
<p> <code>`</code>
 bar</p>
<p> blah</p>
<p> foo
 <code>`</code></p>
</li>
```

**Comment by cebe** [comment]
that's weird, I thought this was working before... Thanks for reporting!

**Comment by cebe** [comment]
your code block is indented 1 space further than the list. Thats why it is picked up as a new paragraph.

Will see if this can be detected better.

**Comment by cebe** [comment]
Fixed, thanks for reporting this!
