### ISSUE TITLE
Github flavoured markdown nest code blocks with language in em

### ISSUE THREAD

**Issue by snakevil** [cebe/markdown#133]
Markdown source

```
\```bash
iptables -t nat -N freedom-https
iptables -t nat -A freedom-https -j ACCEPT

iptables -t nat -A freedom -j freedom-https
iptables -t nat -A freedom -p tcp -j REDIRECT --to-ports <SS-REDIR-PORT>
\```
```

was parsed into

```html
<pre><em><em><em><code class="  language-bash">iptables -t nat -N freedom-https
iptables -t nat -A freedom-https -j ACCEPT

iptables -t nat -A freedom -j freedom-https
iptables -t nat -A freedom -p tcp -j REDIRECT --to-ports &lt;SS-REDIR-PORT&gt;
</code></em></em></em></pre>
```

**Comment by cebe** [comment]
Sorry, I am unable to reproduce the issue with the markdown you have given here. Can you try to reproduce it on http://markdown.cebe.cc/try and paste the link here?

**Comment by snakevil** [comment]
Yes, the Try It! made correct codes which are different from my solution.

I'm using v1.1.1 with the following codes, is there anything wrong?

```php
        $o_mdp = new markdown\GithubMarkdown();
        $o_mdp->html5 = true;
        $a_fields['content'] = $o_mdp->parse($markdown);
```

**Comment by cebe** [comment]
no, code looks okay, is `markdown\GithubMarkdown()` the direct class from this repo or did you extend it?

**Comment by snakevil** [comment]
No, I did composer require the package directly.

**Comment by cebe** [comment]
Sorry, but I am unable to reproduce this and I can not see where `<em>` should come from in the above code...

**Comment by snakevil** [comment]
Please take a look at [the parsed page](https://scatbay.com/a/2014-07/%E5%A6%82%E4%BD%95%E5%9C%A8%E8%B7%AF%E7%94%B1%E5%99%A8%E4%B8%AD%E5%AE%9E%E7%8E%B0%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%EF%BC%9F) and [the source codes](https://scatbay.com/a/2014-07/%E5%A6%82%E4%BD%95%E5%9C%A8%E8%B7%AF%E7%94%B1%E5%99%A8%E4%B8%AD%E5%AE%9E%E7%8E%B0%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%EF%BC%9F.md).

**Comment by snakevil** [comment]
Hmm, it seems that the problem was caused by `**注意：*\<SS-LOCAL-PORT>* 是 /usr/bin/ss-local 本地端口。**`. I copied the source codes from a gist, but this parser works a little different.

**Comment by cebe** [comment]
Passing all that to http://markdown.cebe.cc/try does not cause any issues for me...

**Comment by cebe** [comment]
Note, that the `\` before `\<SS-LOCAL-PORT>` will cause it to be a real HTML tag. If you remove the `\` you get the following: http://markdown.cebe.cc/try?flavor=gfm&text=**%E6%B3%A8%E6%84%8F%EF%BC%9A*%3CSS-LOCAL-PORT%3E*+%E6%98%AF+%2Fusr%2Fbin%2Fss-local+%E6%9C%AC%E5%9C%B0%E7%AB%AF%E5%8F%A3%E3%80%82**

**Comment by snakevil** [comment]
OK. Got it! Thanks for your help!
