### ISSUE TITLE
Please expand installation instructions

### ISSUE THREAD

**Issue by dafydd2277** [cebe/markdown#137]
PHP 5.4.16 on CentOS 7.2.

Composer installed into `/usr/local/bin` without problems, and declared my `php.ini` file correct. Composer then installed cebe/markdown without problems.

I added the line `$parser = new \cebe\markdown\GithubMarkdown();` and got

```
Fatal error: Class 'cebe\markdown\GithubMarkdown' not found in /path/to/index.php on line <line>
```

I added these lines ahead of the `$parser` declaration

```
$path = '/usr/local/bin/vendor/';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);
```

and got the same error message.

Should I have inferred an `include()` or `required()` statement from the instructions? Or, can namespacing be translated into a directory search path?

Thanks!

**Comment by josegonzalez** [comment]
With composer, you need to require the `vendor/autoload.php` if you aren't already doing so in a framework or toolkit. [Thats just how it works](https://getcomposer.org/doc/01-basic-usage.md#autoloading), nothing specific to cebe/markdown.
