### ISSUE TITLE
 Warning: Class __PHP_Incomplete_Class has no unserializer

### ISSUE THREAD

**Issue by samirspatel** [cebe/markdown#138]
Getting this error when trying to install on php7 using symfony 3.2

**Comment by samirspatel** [comment]
I figured this to be a cache issue in symfony. I had to remove the cache directory using `rm` and will still leave this issue open in case you have some ideas.

**Comment by cebe** [comment]
how is this related to my library? how did you install it? also is there a stack trace for the error?
