### ISSUE TITLE
Exception thrown on lines with spaces after list

### ISSUE THREAD

**Issue by czim** [cebe/markdown#145]
Rendering markdown as HTML throws an `ErrorException: Uninitialized string offset: 0` in [LinkTrait `identifyReference()`](https://github.com/cebe/markdown/blob/master/inline/LinkTrait.php#L249).

This happens with the following markdown:

```markdown
- List Item

  
Line to make sure empty lines with spaces are kept
```

The white-space is imporant here, which is:

```
- List Item
<doesn't matter, empty line or some spaces>
<at least two spaces>
Line to make sure empty lines with spaces are kept
```

As soon as the above appears in a document, the error occurs.

**Comment by cebe** [comment]
isn't this fixed by https://github.com/cebe/markdown/commit/7e6fce6b656603c1289a45a41bca065ee8cf3058 ?

**Comment by czim** [comment]
It may be! But since `empty('  ')` is `false`, I'm not 100% on that and would have to check against my example markdown above.

**Comment by cebe** [comment]
made it more robust with 4225204, thanks for reporting!
