### ISSUE TITLE
*** --- Not converting to Horizontal Rule HR tag

### ISSUE THREAD

**Issue by christoferd** [cebe/markdown#148]
Cannot manage to get a HR happening.
Would like "-----" and/or "*****" to convert to a HR line.

---

Tried: Standard, Extra, GitHub
All of which did not produce a line.

PS: I noticed that in GitHub, there needs to be a couple of line carriage breaks before and after the dashes (a clear blank line before and after).... is that the same with cebe/markdown? .... in my use case it still doesn't work with extra line endings.

---

In Version 1.1.1

**Comment by cebe** [comment]
I tried a few examples and they all seem to work fine:

http://markdown.cebe.cc/try?flavor=default&text=a%0D%0A%0D%0A---%0D%0A%0D%0Atest
http://markdown.cebe.cc/try?flavor=gfm&text=a%0D%0A%0D%0A---%0D%0Atest
http://markdown.cebe.cc/try?flavor=gfm&text=a%0D%0A%2A%2A%2A%0D%0Atest
http://markdown.cebe.cc/try?flavor=gfm&text=a%0D%0A%2A%2A%2A%2A%2A%0D%0Atest

can you give an example that does not work?

**Comment by cebe** [comment]
closed until more feedback is provided.
