### ISSUE TITLE
table align does not always work

### ISSUE THREAD

**Issue by dakira** [cebe/markdown#150]
Using the example from the markdown extra site does not properly align the value column in any flavour.

| Item      | Value  |
| --------- | -----: |
| Computer  | $1600  |
| Phone     |   $12  |
| Pipe      |    $1  |

```
| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |
```

**Comment by cebe** [comment]
Unable to reproduce this issue, added a test to verify it: fccb6ac

**Comment by cebe** [comment]
Seems this was not working in 1.1.1 but its working now.

**Comment by cebe** [comment]
probably related to #128

**Comment by dakira** [comment]
When I tried this, it didn't work on the "try" site. Now it does, so I guess it was related to something you did in the meantime. ;) Thanks for fixing.
