### ISSUE TITLE
Extensions list is out of date

### ISSUE THREAD

**Issue by davidnewcomb** [cebe/markdown#159]
In the README.md file:

`kartik-v/yii2-markdown` now uses [michelf's](https://github.com/michelf/php-markdown) markdown instead of cebe. See https://github.com/kartik-v/yii2-markdown/blob/master/composer.json

**Comment by cebe** [comment]
Seems it has never used it but has planned to use it in 2014 :)

> https://github.com/kartik-v/yii2-markdown/issues/17#issuecomment-40749471
> Note though... I have a plan to upgrade the Markdown parser using cebe's Markdown parser down the line (maybe sometime in May when he adds the MarkdownExtra support).

I'll remove the line from readme for now :)

**Comment by cebe** [comment]
Fixed, thanks for the hint!
