### ISSUE TITLE
ListTrait looping through all lines

### ISSUE THREAD

**Issue by jeff-studionone** [cebe/markdown#164]
Hey, guys, I wonder why do you loop through all lines even if you have the `$current` 
It wouldn't be faster to go directly to that line and consume it?

[ListTrait.php](https://github.com/cebe/markdown/blob/530bc7dcbdfea5ad2da030110ee3ac07cc797f90/block/ListTrait.php#L81)

**Comment by cebe** [comment]
That code does not loop all lines, it starts at `$current`.

`$i = $current` is executed on start of the loop, so I starts at current line and not at `0`.

**Comment by jeff-studionone** [comment]
yes, you are right. Thank you
