### ISSUE TITLE
Potential XSS in link rendering

### ISSUE THREAD

**Issue by gdemarcsek** [cebe/markdown#168]
It seems `LinkTrait` tries to prevent XSS by using `htmlspecialchars` here when rendering markdown links: https://github.com/cebe/markdown/blob/530bc7dcbdfea5ad2da030110ee3ac07cc797f90/inline/LinkTrait.php#L230

However, this is insufficient, as an attacker could use the payload:

`javascript:document.write(...)`

to create a link that would execute potentially malicious JS when the victim clicks on it. Based on how the API is constructed, I think this is the library's responsibility to take care of. I would suggest to use the Latte template framework (https://latte.nette.org/en/) as that supports some level of context sensitive auto escaping: https://latte.nette.org/en/guide#toc-link-checking  instead of constructing the HTML by concatenating strings.

**Comment by samdark** [comment]
It doesn't try doing that. See https://github.com/cebe/markdown#security-considerations-

**Comment by cebe** [comment]
As pointed out by @samdark you need to apply additional filtering to get secure output. htmlspecialchars is used to create valid HTML, e.g. convert `&` to `&amp;`.
