### ISSUE TITLE
Difference traditional and GitHub markdown

### ISSUE THREAD

**Issue by zhukovsergei** [cebe/markdown#171]
Hello I have some question, where I can find the difference between versions of parser? For example traditional and GitHub. Thanks a lot.

**Comment by samdark** [comment]
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by zhukovsergei** [comment]
> https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
Yes this is link I have too. But what is the traditional markdown, I want to find out the difference.

**Comment by cebe** [comment]
There are links to the different flavors in the README:

https://github.com/cebe/markdown#what-is-this-

> Currently the following markdown flavors are supported:
> 
> -  Traditional Markdown according to http://daringfireball.net/projects/markdown/syntax
> -  Github flavored Markdown according to https://help.github.com/articles/github-flavored-markdown
> -  Markdown Extra according to http://michelf.ca/projects/php-markdown/extra/ (currently not fully supported WIP see #25)
