### ISSUE TITLE
Definition list is not rendered

### ISSUE THREAD

**Issue by marcinkorytkowski** [cebe/markdown#173]
Follow documentation for definition list you need use code:
```
Apple
:   Pomaceous fruit of plants of the genus Malus in the family Rosaceae.
```
but it not works.

**Comment by cebe** [comment]
which documentation is that? and which parser class are you using?

**Comment by marcinkorytkowski** [comment]
There is in that documentation: http://michelf.ca/projects/php-markdown/extra/
Ok, sorry, I did't notice your comment (https://github.com/cebe/markdown/issues/25). It is not implemented yet. Sorry again.
