### ISSUE TITLE
renderLink() breaks URLs with query params

### ISSUE THREAD

**Issue by jmauzyk** [cebe/markdown#182]
We have a Craft CMS site that uses this package via Yii2. The body of our account activation emails is rendered from markdown and we're running into broken links that prevent users from completing registration.

The activation link URLs have a format similar to `https://craftsite.com/login/pass?code=SEjpQz7MDIhMSmU4IY1xtNEDiClcAqwr&id=9ca06bc2-196a-4734-a1e0-7e98efb90bc3`

However during parsing, `renderLink()` returns a link with the URL `https://craftsite.com/login/pass?code=SEjpQz7MDIhMSmU4IY1xtNEDiClcAqwr&amp;id=9ca06bc2-196a-4734-a1e0-7e98efb90bc3`

This is due to `htmlspecialchars($block['url'], ENT_COMPAT | ENT_HTML401, 'UTF-8')` (LinkTrait.php line 230) converting `&` to `&amp;`, which breaks the URL.

I'm wondering if it's necessary for any encoding of the URL to take place at all. Shouldn't it be incumbent on the author/system creating the URL to make sure it is encoded correctly? If there needs to be encoding, it seems like `htmlspecialchars()` is the wrong choice, as some of the characters it transposes are special/reserved URL characters, while others are unsafe characters that would be better handled with `urlencode()` or similar.

Is this something that can be fixed and released quickly?

**Comment by samwilson** [comment]
What actual error are you seeing?

Special characters such as `&` in a URL in an `href` attribute are supposed to be HTML-encoded, so a link such as this is correct: `<a href="https://example.org?a=b&amp;c=d">test</a>`.

Could it be that the HTML being output by this library is being double-encoded? i.e. your link looks like `https://craftsite.com/login/pass?code=SEjpQz7MDIhMSmU4IY1xtNEDiClcAqwr&amp;amp;id=9ca06bc2-196a-4734-a1e0-7e98efb90bc3`?
