### ISSUE TITLE
Github flavoured markdown is missing syntax highlighting

### ISSUE THREAD

**Issue by mikehaertl** [cebe/markdown#44]
As the title says. You could perhaps use either [PEAR Text highlighter](http://pear.php.net/package/Text_Highlighter/) (Also used by Yii1) or [GeSHi/geshi-1.0](https://github.com/GeSHi/geshi-1.0)

**Comment by mdmunir** [comment]
UP. Is any new news?

**Comment by cebe** [comment]
Yii2 API doc has code highlighting https://github.com/yiisoft/yii2-apidoc/blob/master/helpers/ApiMarkdown.php#L87-L119 you can copy that.

**Comment by cebe** [comment]
not going to add a depdendecy to this lib. syntax highlighting can be added easily by extending the class.
