### ISSUE TITLE
Leanpub Markdown Support

### ISSUE THREAD

**Issue by josegonzalez** [cebe/markdown#51]
Docs are here: https://leanpub.com/help/manual

I have a partial implementation [here](https://gist.github.com/josegonzalez/ed3df2db9e20a81f77a0) (no tests, just my own checking of things)

Also in that gist is a partial list of things we need to support in a LeanpubMarkdown parser

**Comment by claudiosw** [comment]
@josegonzalez, have you implemented it? 
The link is not working anymore.

**Comment by cebe** [comment]
not going to add it unless implementation is provided by someone else.
