### ISSUE TITLE
Use DOMDocument for html parsing?

### ISSUE THREAD

**Issue by donquixote** [cebe/markdown#52]
_Disclaimer: This question is mostly out of selfish curiosity._

Background: I was trying to get the best out of a number of Markdown-related Drupal modules, and ended up writing my own version of the `{.className#id}` mechanic. Then I went around looking at different Markdown implementations in PHP, and found this one, which is probably the best currently available (but [not used in the Drupal markdown module yet](https://drupal.org/node/2288033)).

Looking at the main Markdown class, I have two observations:
1. It is a clear improvement to older implementations.
2. The class is quite big (though smaller than other things I've seen). For my taste, further splitting it up would be a good idea. But I did not look close enough to decide if this is possible.
3. A lot of code is there to deal with HTML parsing. The class would be a lot smaller without that.

So, here is the idea I had. Probably you already thought about this, and decided that it won't work.
1. Parse the text with DOMDocument.
2. Walk through the DOM tree and look for text nodes. Process the text nodes for markdown syntax.

Some markdown stuff needs to look at more than one text node. E.g. bullet lists, if there is e.g. a html span in one of the list items. However, all bullets of a bullet list can be expected to be on the same level of the DOM tree.

Maybe some special handling needs to be done for html characters that are backslash-escaped..

I do not claim that this is going to be easier. In fact, I have no idea.
I am only asking if there is a good reason not to do this.
I also don't know yet what I will do with this information. Maybe some day I will contribute.

**Comment by cebe** [comment]
since this issue has been created the library has go an abstract syntax tree, not using DOM as it is not only HTML. Nothing to do here as far as I see.
