### ISSUE TITLE
Custom tags/extensions

### ISSUE THREAD

**Issue by dolfinitylearning** [cebe/markdown#55]
A nice thing about ReST is its standard for adding custom directives. Would such a thing be useful in cebe/markdown?

Kramdown does this:

{::comment}
This is a comment which is
completely ignored.
{:/comment}

Inline {::nomarkdown}something here{:/}!

{::options auto_ids="false" /}

An alternative:

@tag arg arg
content content content

content content content
/@tag

Docutils (the lib with the ReST parser) has a nice Directive class that does some of the parsing for dumb bunnies like me. For example:

``` python
class Exercise(Directive):
    has_content = False
    required_arguments = 1

    def run(self):
        result = '[[[cycoexercise:' + self.arguments[0] + ']]]\n'
        raw_node = nodes.raw('', result, format='html')
        return [raw_node]
```

Given a tag like this...

.. exercise:: 666

... the Directive class would pick out the 666 and supply it to the subclass in `self.arguments`. If the tag has content, it shows up in `self.content`. You can do this...

``` python
        self.state.nested_parse(
            self.content,
            self.content_offset,
            content_node
        )
```

... if the content of the custom tag is to contain ReST. 

Any chance of something like this?

Kieran

**Comment by cebe** [comment]
I read the issue twice but I do not understand what to do with it. This library implements markdown parsing using extisting standards, I am not going to develop new markdown syntax. That is possible in your own application or library by extending the classes provided by this library.
