### ISSUE TITLE
Deactivate some functionalities ?

### ISSUE THREAD

**Issue by Soullivaneuh** [cebe/markdown#83]
Hi and thanks for you project. :+1: 

I created my own MarkdownParser and I want to deactivate some functionalities like title and raw html parsing.

What is the better way to do that ? Nothing on the documentation, it could be good to have a section for that! :)

Thanks.

**Comment by cebe** [comment]
The README now has a section that explains it: https://github.com/cebe/markdown#composing-your-own-markdown-flavor
